---
title: "J20 by subject analysis"
author: "Iris Oren"
date: "14/06/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r initialisation, include=TRUE, echo = FALSE}
AnimalIDCurrent<-"JF110"
DataFile<-"~/Dropbox/ANALYSIS/J20_EEG_Manuscript/Output/SCPPDataframeAll.csv"

#Load packages
library(lubridate)
library(dplyr)
library(lazyeval) #Needed for using ggplot2 library
library(ggplot2)
library(grid)

#Import data and filter for animal
Dataframe<-read.csv(DataFile)
Dataframe<-filter(Dataframe, AnimalIDVariable==AnimalIDCurrent)
```

#`r AnimalIDCurrent`

###Dataloss over time
```{r DatalossOverTime, include=TRUE, echo = FALSE}
DataLossOverTime<-ggplot(Dataframe, aes(x=strptime(TimeOfDay, format = "%Y-%m-%d %H:%M:%S"), y=Loss)) + xlab("Date") + ylab("Loss")
DataLossOverTime<-DataLossOverTime + geom_point() +
  geom_hline(yintercept = 20)
DataLossOverTime
```

###Filter out loss intervals
This accounts for when transmitter was switched off
```{r FilterOutLoss, include = TRUE, echo = FALSE}
LossThresholdForFiltering=90
Dataframe<-filter(Dataframe, Loss<LossThresholdForFiltering)
```

###Spike count over time

```{r SpikeCountOverTimeControl, include=TRUE, echo = FALSE}
SpikeCountOverTime<-ggplot(Dataframe, aes(x=strptime(TimeOfDay, format = "%Y-%m-%d %H:%M:%S"), y=SpikeCount, colour=Treatment)) + xlab("Date") + ylab("Spikes/8s")
SpikeCountOverTime<-SpikeCountOverTime + geom_point()
SpikeCountOverTime
```

###Polar histogram of IIS from neuroarchiver in control condition
```{r PolarHistogram, include=TRUE, echo = FALSE}
DataframeControl<-filter(Dataframe, Treatment=="Control")
#Manually make new dataframe for histogram plotting. Intialise
SpikeCountHistDF<-data.frame(SpikeCount=double(), HourBin=integer())
#First get the hour of each interval in the dataframe

DataframeControl$TimeOfDay<-strptime(DataframeControl$TimeOfDay, "%Y-%m-%d %H:%M:%S")

DataframeControl$HourOfEvent <- hour(DataframeControl$TimeOfDay)

DataframeSelect<-select(DataframeControl, SpikeCount, HourOfEvent)
for(Hour in 0:23){
  DataframeTemp<-filter(DataframeSelect, HourOfEvent==Hour)
  TotalSpikeCount<-sum(DataframeTemp$SpikeCount)
  TotalHours<-nrow(DataframeTemp)
  TempDF<-data.frame(SpikeCount=TotalSpikeCount/TotalHours, HourBin=Hour+0.5)
  SpikeCountHistDF<-rbind(SpikeCountHistDF, TempDF)
}

SpikeCountHistDF$Light<-SpikeCountHistDF$HourBin %in% seq(7.5, 18.5)

SpikeCountHist<-ggplot(SpikeCountHistDF, aes(x=HourBin, y=SpikeCount, fill=Light)) + geom_bar(stat = "identity")
SpikeCountHist <- SpikeCountHist +
            xlab("Hour") +
            ylab("Spike probability") +
            scale_x_continuous(limits = c(0,24), expand = c(0,0), breaks = seq(0, 23, 2)) +
            scale_fill_grey(labels=c("Off", "On")) +
            coord_polar(start = 0) 
SpikeCountHist
```
